name: Practice CI with GitHub Actions using Ant and JUnit

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
       - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
        run: mkdir staging && cp dist/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      

      - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
        uses: actions/upload-artifact@v1
        with:
          name: DOWNLOAD-JAR-WAR-HEREr # Bản build được đánh version 1.0-SNAPSHOT
          path: staging
